name: Sequencial Job

on:
  workflow_dispatch:
  
jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:      
      - name: Run a one-line script
        run: echo Hello from Planet 11
  
  jobB:
    runs-on: ubuntu-latest
    needs: [jobA]
    steps:    
      - name: Run a multi-line script
        run: |
          echo Hello from Planet 22
          echo Hello from Planet 33
